### ISSUE TITLE
Using any command causes spotify to not automatically play next track

### ISSUE THREAD

**Issue by hamannjames** [hnarayanan/shpotify#80] opened 2017-09-21 02:10 UTC
This is a very weird thing I keep running into. When I use a command spotify will respond, but the next song in a playlist won't automatically play. When I use the next command, it tells me spotify is paused. I have to open up my app and manually go to each song to play. Only doing a "clean" re-install of spotify fixes things. I have had to re-install a couple times. It's very strange.

I am on a mac

**Comment by hnarayanan** [comment] 2017-11-04 19:04
I am sorry, I tried quite a bit but I am unable to reproduce this. Am closing this issue now, but please re-open it later if you have a concrete set of steps to reproduce the problem.

**Closed by hnarayanan** 2017-11-04 19:05 UTC
