### ISSUE TITLE
Spotify URI not working

### ISSUE THREAD

**Issue by andy4thehuynh** [hnarayanan/shpotify#52] opened 2016-09-18 02:05 UTC
The uri link for Final Countdown on Spotify is `spotify play uri spotify:track:3MrRksHupTVEQ7YbA0FsZK. It returns this for me:

`No results when searching for uri spotify:track:79BtIFYdWgo9FZiotlcNks`

Anyone else getting this?

Btw, awesome project. Dig it.

**Comment by hnarayanan** [comment] 2016-09-18 05:50
Are you using the most up-to-date commit of the project? I asked because URI-related code was changed yesterday.

**Comment by andy4thehuynh** [comment] 2016-09-18 06:47
I just pulled it, looks like URI might be deprecated?

**Comment by hnarayanan** [comment] 2016-09-18 08:03
Please check the comments in a PR I recently merged from @ericmarkmartin: https://github.com/hnarayanan/shpotify/pull/48

There is chance that something either broke accidentally or behaviour that changed that's causing your problem. I tested it casually and it worked for me, but please let me know if you find something else out.

**Comment by ericmarkmartin** [comment] 2016-09-18 18:21
You are running `./spotify`, not `spotify`, right?

**Comment by hnarayanan** [comment] 2016-09-18 21:16
@andy4thehuynh: I am not able to reproduce your bug either with the current `spotify`.

**Comment by hnarayanan** [comment] 2016-09-18 21:17
Enjoying some *Final Countdown* as a result.

**Comment by ericmarkmartin** [comment] 2016-09-18 21:19
This made me wonder if it might make sense to include a spotify --version command. Thoughts?

**Comment by hnarayanan** [comment] 2016-09-18 21:21
This is not a bad idea. But after `1.2`, which only needs this issue to be resolved. `1.3` will be all about cleaning up the output and not new features. A version command will fit well there.

Also, Andy, you should be using the even more awesome `spotify play final countdown` UI. ⭐

**Comment by ericmarkmartin** [comment] 2016-09-18 21:22
Got it. I'll make an issue and if you can tag it with the `1.3` milestone that would be cool.

**Comment by ericmarkmartin** [comment] 2016-09-18 21:27
Ah, I have an idea for a makeshift version to close out this issue. @andy4thehuynh, could you run `spotify vol 50` and let me know if there's any output?

**Comment by andy4thehuynh** [comment] 2016-09-18 21:50
@ericmarkmartin I ran `spotify vol 50`.. the output is at half in Spotify.

@hnarayanan I'll try running ./shpotify and pull down the script. Will follow up.

**Comment by ericmarkmartin** [comment] 2016-09-18 21:52
@andy4thehuynh I should have been more specific. Did you see an output message in terminal, or did you just get the prompt without anything being printed to stdout?

**Comment by andy4thehuynh** [comment] 2016-09-18 23:09
@ericmarkmartin no output to stdout. It adjusted my Spotify volume, though.

**Comment by hnarayanan** [comment] 2016-09-19 05:39
Thank you, then you're definitely running an older version of the code. Please make sure you git pull and run `./spotify` within the folder you just pulled.

I am going to close this issue as I'm quite certain your problem will be resolved then. But feel free to reopen it if not.

**Closed by hnarayanan** 2016-09-19 05:39 UTC
Labels: bug
