### ISSUE TITLE
'spotify quit' quits closes terminal window as well

### ISSUE THREAD

**Issue by ryanyz10** [hnarayanan/shpotify#97] opened 2018-04-11 20:54 UTC
Some weird behavior I've bee running into: 'spotify quit' also closes my terminal window that I'm working in. Is this expected behavior or a bug? 

Shell is zsh, terminal is iTerm2.

![kapture 2018-04-11 at 15 51 09](https://user-images.githubusercontent.com/6510606/38642745-99f5ddb6-3da0-11e8-8457-e5541ec9ae7a.gif)

**Comment by hnarayanan** [comment] 2018-04-12 10:45
It is not the intended behaviour, and I am not able to reproduce it in my setup (where it simply closes spotify as it should). I am running `zsh` on Apple's default `Terminal.app`.

**Comment by ryanyz10** [comment] 2018-04-12 13:39
Maybe it's a problem with iTerm then, I'll see if I can look into it but I don't know much, if any, shell.

**Comment by dmofot** [comment] 2018-04-24 17:11
In iTerm2 v3.1.6 using bash shell, `spotify quit` does not close iTerm2.  So it's possibly a combination of iTerm2 and zsh, but it could also be something with @ryanyz10  specific terminal/shell settings.

**Comment by hnarayanan** [comment] 2019-03-24 23:08
I recently merged a PR that prompted me to review and clean up the use of `break`s and `exit`s.

This particular case, I've used `exit 0` as technically that's what this shell script should do when attempting to quit the Spotify app.

**Closed by hnarayanan** 2019-03-24 23:08 UTC

**Comment by ZachAttackMLR** [comment] 2019-04-26 18:59
I ran into this issue yesterday using the built in terminal app on macOS running zsh. I used @ryanyz10 's fix and made a gif of it in case anyone else runs into this issue.

![spotifyQuitFix](https://user-images.githubusercontent.com/17120115/56830089-0c414f80-682b-11e9-9ba0-2cd53bd0f027.gif)
