### ISSUE TITLE
"spotify next" bug issue

### ISSUE THREAD

**Issue by BradleyJHumble** [hnarayanan/shpotify#79] opened 2017-09-05 17:26 UTC
It worked once for me. Now it will shift to the next song but not play it saying that "Spotify is currently paused". It is weird because it would be playing a song and when I enter Spotify next this bug pops up. Originally it worked but after I tried all the other commands it wouldn't work again. I tried restarting the terminal but it still does it for me. 
![screen shot 2017-09-05 at 12 26 10 pm](https://user-images.githubusercontent.com/23151612/30073999-6fb3483e-9235-11e7-98d3-c846fe3c847e.png)

**Comment by BradleyJHumble** [comment] 2017-09-05 17:30
Oh wow right when I post the bug I got it to work. Ok so this error happens if you have the spotify desktop app open and clicked to change the playlist. Or at least that is how I encountered the bug. But regardless this is a bad since the playlist command doesnt work either so this bug is another one to add to the list.

**Comment by hnarayanan** [comment] 2017-11-04 19:07
Much like #80, I am not able to reproduce this. And I tried quite a bit.

Closing this issue now, but please reopen this if it is bothersome.

**Closed by hnarayanan** 2017-11-04 19:07 UTC
